# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image Tag'
        required: true
env:
  REGISTRY: ghcr.io
  GITHUB_REPOSITORY: ${{ github.repository }}

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Downcase IMAGE_NAME
        run: echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Set Image Tag Latest
        run: echo "IMAGE_LATEST=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" >> ${GITHUB_ENV}
      
      - name: Set Image Tag Version
        run: echo "IMAGE_VERSION=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.tag }}" >> ${GITHUB_ENV}
     
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_LATEST }}
            ${{ env.IMAGE_VERSION }}
          platforms: linux/arm64,linux/arm/v7,linux/amd64
          labels: |
            org.opencontainers.image.title=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=https://github.com/${{ env.GITHUB_REPOSITORY }}
            org.opencontainers.image.source=https://github.com/${{ env.GITHUB_REPOSITORY }}
            org.opencontainers.image.version=${{ inputs.tag }}
            org.opencontainers.image.created=${{ github.event.repository.pushed_at }}
            org.opencontainers.image.revision=${{ github.sha }}
      
      - name: Creating Summary
        run: |
          echo "## Release Images 🚀" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Latest:  ${{ env.IMAGE_LATEST }}" >> $GITHUB_STEP_SUMMARY
          echo "- Version: ${{ env.IMAGE_VERSION }}" >> $GITHUB_STEP_SUMMARY